apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mui-pro-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: mui-pro-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mui-pro-app
                port:
                  number: 80
